export default [
  {
    path: '/user/login',
    layout: false,
    name: 'login',
    component: './user/login',
  },
  {
    path: '/user',
    routes: [
      {
        path: '/user/center',
        name: 'center',
        locale: 'menu.user.center',
        icon: 'user',
        hideInMenu: true,
        component: './user/center',
      },
      {
        path: '/user',
        redirect: '/user/center',
      },
    ],
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    icon: 'dashboard',
    access: 'canAdmin',
    component: './dashboard',
  },
  {
    path: '/devices',
    name: 'devices',
    icon: 'desktop',
    access: 'canDevicesView',
    component: './devices',
  },
  {
    path: '/address-book',
    name: 'addressBook',
    icon: 'contacts',
    routes: [
      {
        path: '/address-book',
        redirect: '/address-book/personal',
      },
      {
        name: 'personal',
        icon: 'user',
        path: '/address-book/personal',
        component: './address-book/personal',
      },
      {
        name: 'shared',
        icon: 'team',
        path: '/address-book/shared',
        component: './address-book/shared',
      },
      {
        name: 'shared',
        path: '/address-book/shared/:guid',
        component: './address-book/shared/detail',
        hideInMenu: true,
      },
    ],
  },
  {
    path: '/groups',
    name: 'groups',
    icon: 'team',
    access: 'canGroups',
    routes: [
      {
        path: '/groups',
        redirect: '/groups/user',
      },
      {
        name: 'user',
        icon: 'user',
        path: '/groups/user',
        access: 'canUserGroupsView',
        component: './groups/user',
      },
      {
        name: 'user',
        path: '/groups/user/:guid',
        access: 'canUserGroupsView',
        component: './groups/user/detail',
        hideInMenu: true,
      },
      {
        name: 'device',
        icon: 'device',
        path: '/groups/device',
        access: 'canAdmin',
        component: './groups/device/list',
      },
      {
        name: 'device',
        path: '/groups/device/:guid',
        access: 'canAdmin',
        component: './groups/device/detail',
        hideInMenu: true,
      },
    ],
  },
  {
    path: '/users',
    name: 'users',
    icon: 'user',
    access: 'canUsersView',
    component: './users',
  },
  {
    path: '/roles',
    name: 'roles',
    icon: 'audit',
    access: 'canAdmin',
    component: './roles',
  },
  {
    path: '/audits',
    name: 'audits',
    icon: 'FileSearchOutlined',
    access: 'canAuditConnectionAccess',
    routes: [
      {
        path: '/audits',
        redirect: '/audits/conn',
      },
      {
        name: 'conn',
        icon: 'link',
        path: '/audits/conn',
        access: 'canAuditConnectionAccess',
        component: './audits/conn',
      },
      {
        name: 'file',
        icon: 'file',
        path: '/audits/file',
        access: 'canAuditView',
        component: './audits/file',
      },
      {
        name: 'alarm',
        icon: 'alert',
        path: '/audits/alarm',
        access: 'canAuditView',
        component: './audits/alarm',
      },
      {
        name: 'console',
        icon: 'code',
        path: '/audits/console',
        access: 'canAuditView',
        component: './audits/console',
        hideInMenu: true,
      },
    ],
  },
  {
    path: '/strategy',
    name: 'strategies',
    icon: 'solution',
    access: 'canStrategiesAccess',
    component: './strategy',
  },
  {
    path: '/custom-client',
    name: 'customClients',
    icon: 'form',
    access: 'canAdmin',
    component: './custom-client',
  },
  {
    path: '/settings',
    name: 'settings',
    icon: 'setting',
    access: 'canAdmin',
    routes: [
      {
        path: '/settings',
        redirect: '/settings/general',
      },
      {
        name: 'general',
        icon: 'setting',
        path: '/settings/general',
        component: './settings/general',
      },
      {
        name: 'smtp',
        icon: 'mail',
        path: '/settings/smtp',
        component: './settings/smtp',
      },
      {
        name: 'oidcProviders',
        icon: 'safety',
        path: '/settings/oidc-providers',
        component: './settings/oidc-providers',
      },
      {
        name: 'ldap',
        icon: 'safety',
        path: '/settings/ldap',
        component: './settings/ldap',
      },
    ],
  },
  {
    path: '/',
    redirect: '/address-book/personal',
  },
  {
    component: '404',
    path: '/*',
  },
];
